version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      timezone: Europe/Prague
    open-pull-requests-limit: 0
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: Deps
