name: Test build

on:
  push:
  schedule:
    - cron: '0 9 * * *' # every day at 9:00

jobs:
  test-build:
    name: Build example (${{ matrix.example }}, node ${{ matrix.node-version }})
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    strategy:
      matrix:
        example: [webpack-with-esm, webpack-with-typescript]
        node-version: [18, 20]

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Set up Node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Fetch Git history
        run: git fetch --no-tags --depth=50 origin main

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Test build
        run: yarn build

      - name: Test example build
        run: cd ./examples/${{ matrix.example }} && yarn && yarn build
