name: Test build

on:
  push:
  schedule:
    - cron: '0 9 * * *' # every day at 9:00

jobs:
  test-build:
    name: Build example (${{ matrix.example }}, node ${{ matrix.node-version }})
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    strategy:
      matrix:
        example: [webpack-with-cjs, webpack-with-esm, webpack-with-typescript]
        node-version: [18, 20]

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up Node
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Fetch Git history
        run: git fetch --no-tags --depth=50 origin main

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Test build
        run: yarn build

      - name: Test example build
        run: cd ./examples/${{ matrix.example }} && yarn && yarn build
