name: Commits Check

on:
  push:
    branches-ignore:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up Node
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
        with:
          node-version: 18

      - name: Fetch Git history
        run: git fetch --no-tags --depth=50 origin main

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run Commitlint
        run: yarn commitlint --color --verbose --from $(git merge-base origin/main HEAD)
