name: Commits Check

on:
  push:
    branches-ignore:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: 18

      - name: Fetch Git history
        run: git fetch --no-tags --depth=50 origin main

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run Commitlint
        run: yarn commitlint --color --verbose --from $(git merge-base origin/main HEAD)
