name: Git Check

on: [pull_request]

jobs:
  block-fixup-merge:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Block fixup commit merge
        uses: 13rac1/block-fixup-merge-action@bd5504fb9ca0253e109d98eb86b7debc01970cdc # v2.0.0
