name: Git Check

on: [pull_request]

jobs:
  block-fixup-merge:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Block fixup commit merge
        uses: 13rac1/block-fixup-merge-action@bd5504fb9ca0253e109d98eb86b7debc01970cdc # v2.0.0
