name: Markdown Link Check

on:
  push:
  schedule:
    - cron: '0 9 * * *' # every day at 9:00

jobs:
  markdown-link-check:
    name: "Markdown link check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1
        with:
          use-verbose-mode: 'yes'
          config-file: '.github/markdown-link-check-config.json'
