name: Markdown Link Check

on:
  push:
  schedule:
    - cron: '0 9 * * *' # every day at 9:00

jobs:
  markdown-link-check:
    name: "Markdown link check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: tcort/github-action-markdown-link-check@75e8eff79b17a74255f5d39b8e8fe66b9ce891f6 # v1.1.0
        with:
          use-verbose-mode: 'yes'
          config-file: '.github/markdown-link-check-config.json'
