name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Create release
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Release
        run: yarn release
