name: Test

on:
  push:
  schedule:
    - cron: '0 9 * * *' # every day at 9:00

jobs:
  test:
    name: Tests and linting
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Set up Node
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
        with:
          node-version: 18

      - name: Fetch Git history
        run: git fetch --no-tags --depth=50 origin main

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Check code-style format
        run: yarn format

      - name: Check types
        run: yarn types

      - name: Unit tests
        run: yarn test:unit
