name: Test

on:
  push:
  schedule:
    - cron: '0 9 * * *' # every day at 9:00

jobs:
  test:
    name: Tests and linting
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 18

      - name: Fetch Git history
        run: git fetch --no-tags --depth=50 origin main

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Check code-style format
        run: yarn format

      - name: Check types
        run: yarn types

      - name: Unit tests
        run: yarn test:unit
